### ISSUE TITLE
I'm getting all these wonderful errors

### ISSUE THREAD

**Issue by Italist** [Gavin770/champGG#2]
![wbsyfjt](https://cloud.githubusercontent.com/assets/4417167/7202860/601d8af2-e516-11e4-8254-8bec3e9e8441.png)

**Comment by Delogrand770** [comment]
Those errors mean your internet connection is having difficulty connecting to the website champion.gg. This can be caused by a slow, disrupted or blocked internet connection.

**Comment by Italist** [comment]
Could you delay the time it waits for the server response and/or give some delay between server requests?
My connection is pretty solid. Imo it was the server rejecting the connection.

**Comment by Delogrand770** [comment]
The program is build on nwjs.io and it uses a built in nodejs library so I
don't think I can extend the timeout request. I can try adding a delay
between requests. I use the program daily but then again my setup is
different then yours so thanks for helping me improve reliability by
reporting the errors you see.

**Comment by Italist** [comment]
That would be awesome! Thanks to you for making this version of the script and taking time to assist me.
I'd have contributed with a push myself but I'm not familiar with the tech you used.

By the way you may find useful for further development this discussion over the skillorder:
https://www.reddit.com/r/leagueoflegends/comments/32ea2b/championgg_item_sets_updated_for_patch_57_script/cqanzco

I'd personally use the last comment on that tree.
Oh by the way, I noticed the ebildude123 guy removed the mana pot for mana less champs on his itemsets generator.
Thanks again.

**Comment by Delogrand770** [comment]
The new version now has a one request at a time mode. You can enable it by clicking the config button and following the last sections instructions.

**Comment by albertogloder** [comment]
Tried it out, worked like a charm. Thanks again!

**Comment by Italist** [comment]
Tried it out, it worked like a charm!

**Comment by Delogrand770** [comment]
I also just implemented the skill order changes you pointed out on reddit. I didn't remove the mana pot from non ap champs that way when people try weird builds they have it at their disposal.

**Comment by Italist** [comment]
OP! You are now exalted with Italist.

**Comment by Delogrand770** [comment]
Thanks! Also you should know I updated it again to prevent the titles of each item section from being cut off. Turns out the League client has a 50 character limit.
