### ISSUE TITLE
Garena Support

### ISSUE THREAD

**Issue by mozophe** [Gavin770/champGG#3]
Not quite an issue but a feature request. Can you add support for garena ?(It manages LoL client in SEA region)

Directory for garena is - C:\Program Files (x86)\GarenaLoL\GameData\Apps\LoL\Game\Config\Champions

You can set riot's directory as default one and give garena as an option ie if checked, it will look for garena folder and try to save there.
Currently, I use your program to generate Item Sets and manually paste there. It would be great help if you can add support for garena.

**Comment by Delogrand770** [comment]
I can definitely add this feature but I'm in the middle of moving. Once I
finish the move I'll add this feature!

**Comment by Delogrand770** [comment]
I have updated the app to support Garena. I'm in NA not Garena but I was able to use your request data to make what I believe to be working Garena support. It is likely you will need to run the app as administrator to work with Garena since the permissions of the program files directory usually don't allow writing/deleting of files.

**Comment by mozophe** [comment]
Thanks for adding support for garena. This works fine when you have a single LoL client installed. Problem is I have installed both LoL NA and Garena. Can you add a check box, which when checked sets default as Garena?
With this I can update whichever client I want to update.

**Comment by Italist** [comment]
Wouldn't you want to update both of them in any scenario? Have champGG to check on both league default locations and add them to a list, displayed in settings. Let the user be able to delete entries from the list and add a custom path. how about that?

**Comment by mozophe** [comment]
This seems to be a better approach but there's a minor issue. Garena servers usually take 1 to 2 weeks to update to latest patch after patch is released on riot servers. This may introduce items from newer version into old LoL version on Garena. Thats why a checkbox is preferred so that user can control if he wants to update garena or not.

**Comment by Delogrand770** [comment]
I'll see what I can do!

**Comment by Delogrand770** [comment]
I have changed a lot but it now works so that you can decide to download the sets for normal league or garena. This required a significant amount of code change so please report any bugs you find.

**Comment by mozophe** [comment]
Thanks for the update. Love the new UI. Tested and working for both Lol NA and Garena.
